### ISSUE TITLE
access and network policy resources are not added to cloudformation resources tab

### ISSUE THREAD

**Issue by kraziii** [schuettc/cdk-bedrock-knowledge-base#1]
Resources created by these methods:

createAccessPolicy, createNetworkSecurityPolicy, createEncryptionSecurityPolicy

need to be returned by custom resource here:

      response.Data = {
        collectionArn: collection.arn!,
        collectionId: collection.id!,
        collectionName: collection.name!,
        collectionEndpoint: collection.collectionEndpoint,
        dataSourceId: dataSource?.dataSource?.dataSourceId,
        knowledgeBaseId: knowledgeBase.knowledgeBase?.knowledgeBaseId,
      };

**Comment by schuettc** [comment]
https://github.com/schuettc/cdk-bedrock-knowledge-base/pull/2

Great!  Thanks!
